FORMAT: 1A
HOST: http://prod.maihama.jp/api/v1/

# maihama API
## このドキュメントについて
- アプリからコールされる web api です。

## カテゴリー一覧取得 [/v1/category/list]
有効なカテゴリー一覧をオーダーID昇順で返却します

### Response [GET]

+ Response 200 (application/json)

    + Body

            {
                "code": 200,
                "contents": [
                    {
                        "_id": "000000000000000000000007",
                        "name": "for FindAllPublishedCategories",
                        "order_id": 0,
                        "published": true,
                        "deleted": false,
                        "created_at": 0,
                        "updated_at": 0
                    },
                    {
                        "_id": "000000000000000000000009",
                        "name": "for FindAllPublishedCategories(this is will be hit)",
                        "order_id": 0,
                        "published": true,
                        "deleted": false,
                        "created_at": 0,
                        "updated_at": 0
                    },
                    {
                        "_id": "000000000000000000000016",
                        "name": "for FindAllPublishedCategories(this is will be hit)",
                        "order_id": 0,
                        "published": true,
                        "deleted": false,
                        "created_at": 0,
                        "updated_at": 0
                    },
                    {
                        "_id": "000000000000000000000008",
                        "name": "for FindAllPublishedCategories",
                        "order_id": 1,
                        "published": true,
                        "deleted": false,
                        "created_at": 0,
                        "updated_at": 0
                    }
                ]
            }


