FORMAT: 1A
HOST: http://prod.maihama.jp/api/v1/

# maihama API
## このドキュメントについて
- apiary(エピアリー)で作成したmaihama API のドキュメントです

## カテゴリー一覧取得 [/v1/category/list]
有効なカテゴリー一覧をオーダーID昇順で返却します

### Response [GET]

+ Response 200 (application/json)

    + Body

            {
                "code": 200,
                "contents": [
                    {
                        "id": "000000000000000000000007",
                        "name": "おすすめ",
                        "orderId": 1,
                        "published": true,
                        "deleted": false,
                        "createdAt": 0,
                        "updatedAt": 0
                    },
                    {
                        "id": "000000000000000000000008",
                        "name": "お笑い",
                        "orderId": 2,
                        "published": true,
                        "deleted": false,
                        "createdAt": 0,
                        "updatedAt": 0
                    },
                    {
                        "id": "000000000000000000000009",
                        "name": "ゲーム",
                        "orderId": 3,
                        "published": true,
                        "deleted": false,
                        "createdAt": 0,
                        "updatedAt": 0
                    }
                ]
            }


